name = "worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[builder_config]
# "npm install && npm run build" won't work here, && will be treated as an arg to npm install
build_command = "npm run build"
upload_format = "modules"
src_dir = "src"
build_dir = "dist"

[durable_objects]
implements = [{class_name = "Counter", namespace_name = "Counter"}]
uses = [{binding = "Counter", namespace_name = "Counter"}]